# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52a8adf7d60e44d182af618d747bb75d4222088c1dd00f7f735c9aaa8cac9212f39742982d9b764aa0280aec30ed7bb479f81ccb9d2203cc9916ca326219b924

test:
  secret_key_base: 58e8450df4ffc2d61269bc73bc5a43d23ffff19d35a09becb2a669f0997aa0a3e7b66a495c8f93445027f4d06fb8de73c93fc07e55363fcdcd2ab2af93b56b5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
